FROM ghcr.io/graalvm/graalpy-community:24.0.1

RUN yum install -y libffi-devel
RUN source /app/graalenv/bin/activate && \
    pip install PyNaCl==1.5.0 bcrypt==4.0.1 cffi==1.15.1 cryptography==41.0.3 paramiko==3.4.0 pycparser==2.22 six==1.16.0


RUN mkdir -p /usr/local/lib/python3.10/site-packages && \
    cp -r /app/graalenv/lib/python3.10/site-packages/* /usr/local/lib/python3.10/site-packages

VOLUME ["/usr/local/lib/python3.10/site-packages"]