version: "3"
services:
  metersphere:
    image: metersphere/metersphere-ce-allinone:v3.x
    container_name: metersphere
    extra_hosts:
      - "task-runner:127.0.0.1"
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8081" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always

