FROM ghcr.io/graalvm/graalpy-community:24.0.1

RUN yum -y install libffi-devel rust cargo && yum clean all

RUN source /app/graalenv/bin/activate && \
    pip install paramiko requests pinyin


RUN mkdir -p /usr/local/lib/python3.10/site-packages && \
    cp -r /app/graalenv/lib/python3.10/site-packages/* /usr/local/lib/python3.10/site-packages

VOLUME ["/usr/local/lib/python3.10/site-packages", "/app/graalenv"]
