FROM registry.fit2cloud.com/metersphere/python:3.10-alpine
 
RUN apk add --update musl-dev gcc cargo build-base libffi-dev openssl-dev 
RUN pip install requests pinyin
 
VOLUME ["/usr/local/lib/python3.10/site-packages"]