FROM registry.fit2cloud.com/metersphere/python:3.10-alpine
 
RUN apk add --update musl-dev gcc cargo
RUN pip install paramiko==2.12.0 cryptography==3.4.7 bcrypt==3.2.0 pynacl==1.4.0 cffi==1.14.6
 
VOLUME ["/usr/local/lib/python3.10/site-packages"]